#!/bin/bash
#
# Copyright (c) 2007 Bradley Taylor, bradley@railsmachine.com
#
# mongrel_cluster       Startup script for Mongrel clusters.
#
# chkconfig: - 85 15
# description: mongrel_cluster manages multiple Mongrel processes for use \
#              behind a load balancer.
#              

PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local:/usr/local/sbin:/usr/local/bin
CONF_DIR=<%= swiftiply_conf_dir %>
CONF=<%= swiftiply_conf %>
PID_DIR=<%= swiftiply_pid_dir %>
PID_FILE=<%= swiftiply_pidfile %>

EVENT=1

RETVAL=0

# Gracefully exit if the controller is missing.
which swiftiply >/dev/null || exit 0

# Go no further if config directory is missing.
[ -d "$CONF_DIR" ] || exit 0

# Thanks Justin Pease!
function generatepid(){
  current_pid=`pgrep -f 'swiftiply -c $CONF'`
	touch $PID_FILE
  pidfile_pid=`cat $PID_FILE`

  if [[ $current_pid = '' ]]; then
    rm $PID_FILE
  elif [[ $pidfile_pid != $current_pid ]]; then
    echo $current_pid > $PID_FILE
  fi
}

case "$1" in
	start)
	  # Create pid directory
	  mkdir -p $PID_DIR
	  # chown $USER:$USER $PID_DIR

	  swiftiply -c $CONF || exit 0
		generatepid
	;;
	stop)
	killall -9 swiftiply
	  swiftiply stop -c $CONF || exit 0
		generatepid
	;;
	restart)
		$0 stop
		$0 start
	;;
	reload)
		killall -HUP swiftiply || exit 0
	;;
  pid)
    generatepid
  ;;
	*)
	  echo "Usage: swiftiply {start|stop|restart|reload|pid}"
	  exit 1
	;;
esac      

exit 0