#!/bin/bash

### BEGIN INIT INFO
# Provides: ejabberd
# Default-Start:  2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: start and stop ejabberd
# Description: monitoring by ejabberd.
### END INIT INFO
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DESC="erlang xmpp messaging server"
NAME=ejabberd
DAEMON=/usr/local/sbin/ejabberdctl
CONFIGFILEDIR=/usr/local/etc/ejabberd
LOGFILE=/usr/local/var/log/ejabberd/$NAME.log
SCRIPTNAME=/etc/init.d/$NAME

# Check if DAEMON binary exist
test -f $DAEMON || exit 0

set -e

case "$1" in
  start)
        echo -n "Starting $DESC: "
        start-stop-daemon --start --quiet \
                --exec $DAEMON -- start
        echo "$NAME."
        ;;
  stop)
        echo -n "Stopping $DESC: "
        start-stop-daemon --stop --quiet \
                --exec $DAEMON -- stop
        echo "$NAME."
        ;;
  restart|force-reload)
        echo -n "Restarting $DESC: "
        start-stop-daemon --stop --quiet --exec $DAEMON -- stop
        sleep 1
        start-stop-daemon --start --quiet --exec $DAEMON -- start
        echo "$NAME."
        ;;
	  *)
	        N=/etc/init.d/$NAME
	        echo "Usage: $N {start|stop|restart}" >&2
	        exit 1   
	        ;;
	esac

	exit 0
